- name: Configure the new VM hostname
  hosts: 10.13.104.41 # replace with cloned virtual machine ip address (if you don't know this go run playblook.yml section first)
  gather_facts: yes
  become: yes
  vars:
    ansible_host: 10.13.104.41 # replace with cloned virtual machine ip address (if you don't know this go run playblook.yml section first)
    ansible_user: sysadmin # replace with your ubuntu template username
    ansible_ssh_pass: "123456" # replace with your ubuntu template password
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: espresso-instance # hostname you want to change to
